### ISSUE TITLE
[Suggestion] Colored lasers

### ISSUE THREAD

**Issue by villager103** [HugoBDesigner/Mari0-Community-Edition#33] opened 2018-05-09 10:35 UTC
Colored lasers are an alternate form of the traditional laser that can be accessed via dropdown menu on regular lasers.

There are 4 colors: Red(default), Blue, Green and Yellow. There are also laser catchers(and reflector cubes, if those are ever implemented) of each color. A laser catcher can only be activated by a laser of the same color. Laser catchers have all 4 of the colors that lasers do, with an additional "Gray" color, which lets any color activate it(selected by default)

All existing lasers in maps are red, and all existing catchers are gray, so compatibility isn't ruined in any way.

Laser catchers(and possibly emitters) will need to have their textures changed to accommodate for this.

This will allow for more complex laser puzzles and laser-based mechanisms.

**Comment by HugoBDesigner** [comment] 2018-05-09 12:44
I'll consider the "specific color" catcher as an extension of #32 , but colored lasers are already going to be possible with #14

**Comment by HugoBDesigner** [comment] 2018-05-09 12:44
Duplicate of #12

**Closed by HugoBDesigner** 2018-05-09 12:44 UTC
Labels: Duplicate
